# Generated by Django 5.2.4 on 2026-07-12 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mix',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mix',
            name='audio_file',
            field=models.FileField(upload_to='mixes/audio/'),
        ),
        migrations.AlterField(
            model_name='mix',
            name='cover_image',
            field=models.ImageField(upload_to='mixes/covers/'),
        ),
        migrations.AlterField(
            model_name='mix',
            name='duration',
            field=models.CharField(blank=True, help_text='Example: 1h 15m', max_length=20),
        ),
        migrations.AlterField(
            model_name='mix',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genre'),
        ),
    ]
