# Generated by Django 5.2.4 on 2026-07-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_mix_likes_mix_views_alter_mix_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='audio_file',
            field=models.FileField(upload_to='mixes/'),
        ),
        migrations.AlterField(
            model_name='mix',
            name='cover_image',
            field=models.ImageField(upload_to='mix_covers/'),
        ),
    ]
