# Generated by Django 5.2.4 on 2026-07-19 17:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_mix_audio_file_alter_mix_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='mix',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
