# Generated by Django 5.2.4 on 2026-08-26 20:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_mix_audio_file_alter_mix_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
