# Generated by Django 5.2.4 on 2026-07-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Visible only to the admin. Can be shared with the customer.'),
        ),
    ]
